### PR TITLE
implement programmatic value reset

### PR DESCRIPTION
**Pull request by jordanjones243**
# Alaska Airlines Pull Request

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

**Fixes:** #64 

## Summary:

_Please summarize the scope of the changes you have submitted, what the intent of the work is and anything that describes the before/after state of the project._

* Add new event `auroMenu-selectValueReset`, causing `value` to be reset when event is fired.
* Add tests to ensure programmatically setting value to a valid value, invalid value and undefined work properly.

## Type of change:

Please delete options that are not relevant.

- [x] New capability
- [ ] Revision of an existing capability
- [ ] Infrastructure change (automation, etc.)
- [ ] Other (please elaborate)

## Checklist:

- [x] My update follows the CONTRIBUTING guidelines of this project
- [x] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

### CODE REVIEW

**Comment by blackfalcon** [comment]
@jordanjones243 please add the issue ID to the end of the commit message.

**Review by blackfalcon — CHANGES_REQUESTED** [review]
We do not have an example or any other documentation update that supports this new feature?

**Review by blackfalcon — CHANGES_REQUESTED** [review]
This fix is confusing me. I see a test added, but I do not see any changes in the demo? 

Also, don't forget to run a build to create all the automated documentation for this repo.

**Comment by jordanjones243** [comment]
> This fix is confusing me. I see a test added, but I do not see any changes in the demo?
> 
> Also, don't forget to run a build to create all the automated documentation for this repo.

There were no changes to the demo, the example was already created under the API tab of combobox. The example was already present, but was not working as we intended because some of our work was lost sometime during the last commit. We added that work back on and then added some tests as well.

**Review by jason-capsule42 — APPROVED** [review]

**Pull request merged**
