### PR TITLE
Bug fixes per review of latest release

### PR DESCRIPTION
**Pull request by jason-capsule42**
# Alaska Airlines Pull Request

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

**Fixes:** #91 #93 #94 #97, #99

## Summary:

_Please summarize the scope of the changes you have submitted, what the intent of the work is and anything that describes the before/after state of the project._

## Type of change:

Please delete options that are not relevant.

- [ ] New capability
- [x] Revision of an existing capability
- [ ] Infrastructure change (automation, etc.)
- [ ] Other (please elaborate)

## Checklist:

- [x] My update follows the CONTRIBUTING guidelines of this project
- [ ] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

### CODE REVIEW

**Comment by blackfalcon** [comment]
A review of issue #91 still exhibits the error. Please see the original issue with some additional findings. 

Recommendation, this issue be addressed in a separate PR as a litany of issues being discovered.

**Comment by blackfalcon** [comment]
Issue #91 obsservations 

1. type `mke` into input
2. See Milwaukee in the dropdown 
3. Tap the `down arrow` key once
4. Hit `enter`
5. See `San Francisco` in the input
6. Click back into the input
7. Unable to clear input with the `x`

Sep-30-2022 11-12-34

Browser: Safari, Version 15.5 (17613.2.7.1.8)

**Comment by blackfalcon** [comment]
Issue #93 observations 

When entering a date into the input, an empty bib appears on the screen. Hitting the `x` does not clear the input value.

Sep-30-2022 11-17-30


Browser: Safari, Version 15.5 (17613.2.7.1.8)

**Comment by blackfalcon** [comment]
Issue #94 observations. 

The data error is corrected. The clear `x` is not working.

**Review by blackfalcon — CHANGES_REQUESTED** [review]
See listed observations.

**Comment by jason-capsule42** [comment]
> Issue #91 obsservations
> 
> 1. type `mke` into input
> 2. See Milwaukee in the dropdown
> 3. Tap the `down arrow` key once
> 4. Hit `enter`
> 5. See `San Francisco` in the input
> 6. Click back into the input
> 7. Unable to clear input with the `x`
> 
> Sep-30-2022 11-12-34 [ Sep-30-2022 11-12-34 ](https://user-images.githubusercontent.com/181089/193331802-b1300b3a-fe53-4f41-879b-7e0225a6371d.gif) [ ](https://user-images.githubusercontent.com/181089/193331802-b1300b3a-fe53-4f41-879b-7e0225a6371d.gif)
> 
> Browser: Safari, Version 15.5 (17613.2.7.1.8)

This is an auro-menu bug. The arrow keys are not skipping over the hidden menu items. Please open a new bug there.

**Comment by jason-capsule42** [comment]
> The data error is corrected. The clear x is not working.

Fixed by using the latest auro-input release.

**Comment by jason-capsule42** [comment]
> Issue #93 observations
> 
> When entering a date into the input, an empty bib appears on the screen. Hitting the `x` does not clear the input value.
> 
> Sep-30-2022 11-17-30 [ Sep-30-2022 11-17-30 ](https://user-images.githubusercontent.com/181089/193332452-b2b6fb91-aacf-45e8-991f-2f25869779fe.gif) [ ](https://user-images.githubusercontent.com/181089/193332452-b2b6fb91-aacf-45e8-991f-2f25869779fe.gif)
> 
> Browser: Safari, Version 15.5 (17613.2.7.1.8)

The empty bib issue is fixed. The X icon is an auro-input issue. It appears that our logic for hiding the X button is the problem. When we go to click on the X icon we we are technically doing a blur away from the input before the click happens on the X. But we only show the X button when the input has focus. While Chrome handles this gracefully, Safari does not.

I've opened this ticket to track work there: https://github.com/AlaskaAirlines/auro-input/issues/195

**Comment by jordanjones243** [comment]
The last commit regarding ticket #97 was done in auro-input and verified through linking, a simple auro-input version update was the change added to this PR. Here is the ticket in auro-input: https://github.com/AlaskaAirlines/auro-input/issues/196

**Comment by jordanjones243** [comment]
I've added another commit to this PR that was another update of the auro-input versioning from this fix: https://github.com/AlaskaAirlines/auro-input/pull/199. It did not make sense to me to create a PR for a change that was already in this PR. I added another commit, rather than a patch to show that we fixed both tickets #97 and #99.

**Comment by blackfalcon** [comment]
There is a lot going on with this update. I'd like to see the input updates released and then the other height bug fix for combobox and then I will do a final eval of this series of updates.

**Review by blackfalcon — DISMISSED** [review]

**Comment by jason-capsule42** [comment]
> Please delete this code https://github.com/AlaskaAirlines/auro-combobox/pull/95/files#diff-d06b32dfa5173b4749d75d64f3cf869b990b2b1f9d896d8a5386e5d0410d3121R14-R20

I can't tell what code you think needs to be deleted from the link.

**Comment by blackfalcon** [comment]
@jason-capsule42 or sure, you have to expand the code to see it. It is lines 14-20. But wait... why are we removing the a11y test? 

The other link is for lines 294-313.

**Review by blackfalcon — APPROVED** [review]

**Comment by blackfalcon** [comment]
:shipit:

**Pull request merged**
